In [1]:
import numpy

In [2]:
vector = [1, 2, 3]

In [3]:
print(type(vector))

<class 'list'>


In [4]:
nvector = numpy.array(vector)
print(type(nvector))

<class 'numpy.ndarray'>


In [5]:
nvector.shape

(3,)

In [6]:
matrix =[
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

In [7]:
nmatrix = numpy.array(matrix)

In [8]:
nmatrix.shape

(3, 3)

In [9]:
j = 3
i = [1, 2, 3]
k = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

x = [
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ],
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ],
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ]
]

In [10]:
print(type(x))

<class 'list'>


In [11]:
narr = numpy.array([1, 2, 3])
narr

array([1, 2, 3])

In [12]:
numpy.resize(narr, (4,4))

array([[1, 2, 3, 1],
       [2, 3, 1, 2],
       [3, 1, 2, 3],
       [1, 2, 3, 1]])

In [13]:
narr.resize((3, 3), refcheck=False)

In [14]:
narr

array([[1, 2, 3],
       [0, 0, 0],
       [0, 0, 0]])

In [15]:
matrix = numpy.ones((5, 4))

In [16]:
matrix

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
matrix = numpy.zeros((4, 4))

In [18]:
matrix

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
numpy.diag(narr)

array([1, 0, 0])

In [20]:
numpy.repeat([4, 3, 2], 5)

array([4, 4, 4, 4, 4, 3, 3, 3, 3, 3, 2, 2, 2, 2, 2])

In [21]:
m1 = numpy.ones((4, 5), int)

In [22]:
m1

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [23]:
m2 = numpy.zeros((4, 5), int)
m2

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [24]:
numpy.vstack([m1, m2])

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [25]:
numpy.hstack([m1, m2])

array([[1, 1, 1, 1, 1, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 0, 0, 0, 0, 0]])

In [26]:
[1, 2, 4] * [2, 3, 4]

TypeError: can't multiply sequence by non-int of type 'list'

In [28]:
x = numpy.array([1, 2, 3])
y = numpy.array([4, 5, 6])
z = x * y
z

array([ 4, 10, 18])

In [29]:
x ** 2


array([1, 4, 9])

In [31]:
x.dot(y)
x

array([1, 2, 3])

In [32]:
narr

array([[1, 2, 3],
       [0, 0, 0],
       [0, 0, 0]])

In [33]:
narr.T

array([[1, 0, 0],
       [2, 0, 0],
       [3, 0, 0]])

In [34]:
narr.astype('f')

array([[1., 2., 3.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)

In [36]:
narr.sum()


np.int64(6)

In [37]:
narr.max()

np.int64(3)

In [38]:
narr.argmax()

np.int64(2)

In [39]:
narr.min()

np.int64(0)

In [41]:
narr.argmin()

np.int64(3)

In [42]:
narr.mean()

np.float64(0.6666666666666666)

In [43]:
narr.std()

np.float64(1.0540925533894598)

In [44]:
mr = numpy.arange(15) ** 2

In [45]:
mr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196])

In [46]:
mr[-6:14:2]

array([ 81, 121, 169])

In [48]:
mr[2]

np.int64(4)

In [49]:
mr[10::-2]

array([100,  64,  36,  16,   4,   0])

In [50]:
mr[:5]

array([ 0,  1,  4,  9, 16])

In [51]:
mr[4:13:4]

array([ 16,  64, 144])

In [52]:
mr[1:4]

array([1, 4, 9])

In [53]:
mr[-10:-2:3]

array([ 25,  64, 121])

In [ ]:
narr = numpy.array(
    []
)