In [1]:
import numpy

In [2]:
vector = [1, 2, 3]

In [3]:
print(type(vector))

<class 'list'>


In [4]:
nvector = numpy.array(vector)
print(type(nvector))

<class 'numpy.ndarray'>


In [5]:
nvector.shape

(3,)

In [6]:
matrix =[
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

In [7]:
nmatrix = numpy.array(matrix)

In [8]:
nmatrix.shape

(3, 3)

In [9]:
j = 3
i = [1, 2, 3]
k = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

x = [
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ],
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ],
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ]
]

In [10]:
print(type(x))

<class 'list'>


In [11]:
narr = numpy.array([1, 2, 3])
narr

array([1, 2, 3])

In [12]:
numpy.resize(narr, (4,4))

array([[1, 2, 3, 1],
       [2, 3, 1, 2],
       [3, 1, 2, 3],
       [1, 2, 3, 1]])

In [13]:
narr.resize((3, 3), refcheck=False)

In [14]:
narr

array([[1, 2, 3],
       [0, 0, 0],
       [0, 0, 0]])

In [15]:
matrix = numpy.ones((5, 4))

In [16]:
matrix

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
matrix = numpy.zeros((4, 4))

In [18]:
matrix

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
numpy.diag(narr)

array([1, 0, 0])

In [20]:
numpy.repeat([4, 3, 2], 5)

array([4, 4, 4, 4, 4, 3, 3, 3, 3, 3, 2, 2, 2, 2, 2])

In [21]:
m1 = numpy.ones((4, 5), int)

In [22]:
m1

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])